version: "3"

services:
  app-producer:
    build: app-producer
    depends_on:
      - rabbitmq
    restart: always
    volumes:
      - ./app-producer:/app
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOST=rabbitmq
  app-service:
    build: app-service
    depends_on:
      - rabbitmq
    restart: always
    volumes:
      - ./app-service:/app
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOST=rabbitmq
  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_NODENAME=rabbit@rabbitmq
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia
      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./rabbitmq/definitions.json:/opt/definitions.json
